// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvtncUEmrzeZEWj9hslxlOO-TLgz9jm8w',
    appId: '1:885236324406:web:1eceda12da3a5f46e5e097',
    messagingSenderId: '885236324406',
    projectId: 'auxilioprofessor-fce60',
    authDomain: 'auxilioprofessor-fce60.firebaseapp.com',
    storageBucket: 'auxilioprofessor-fce60.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDK1TuhCfjd53lI2J4v7M0BEj6dJ4ghpg',
    appId: '1:885236324406:android:c91b3a4afc78f6f8e5e097',
    messagingSenderId: '885236324406',
    projectId: 'auxilioprofessor-fce60',
    storageBucket: 'auxilioprofessor-fce60.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhS3K8KlIs_3FQ1z4A7F_feUFMpvCaDj0',
    appId: '1:885236324406:ios:ed769dd85e8a0ddfe5e097',
    messagingSenderId: '885236324406',
    projectId: 'auxilioprofessor-fce60',
    storageBucket: 'auxilioprofessor-fce60.appspot.com',
    iosBundleId: 'br.com.lucas.auxilioprofessor',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDhS3K8KlIs_3FQ1z4A7F_feUFMpvCaDj0',
    appId: '1:885236324406:ios:0e1e7b61b692e552e5e097',
    messagingSenderId: '885236324406',
    projectId: 'auxilioprofessor-fce60',
    storageBucket: 'auxilioprofessor-fce60.appspot.com',
    iosBundleId: 'br.com.lucas.auxilioprofessor.RunnerTests',
  );
}
